### ISSUE TITLE
Using Multi GPUs

### ISSUE THREAD

**Issue by KevinGoodman** [galatolofederico/clip-glass#11]
When I try the text-to-image task, I always run out of CUDA memory on single GPU.
I try to set the device to 'cuda:0,1' but it doesn't work. 
I get error like this:

```
File "run.py", line 54, in <module>
    problem = GenerationProblem(config)
  File "/home/ubuntu/Documents/clip-glass/problem.py", line 9, in __init__
    self.generator = Generator(config)
  File "/home/ubuntu/Documents/clip-glass/generator.py", line 16, in __init__
    self.CLIP, clip_preprocess = clip.load("ViT-B/32", device=self.config.device, jit=False)
  File "/home/ubuntu/anaconda3/envs/lib/python3.7/site-packages/clip/clip.py", line 137, in load
    model = build_model(state_dict or model.state_dict()).to(device)
  File "/home/ubuntu/anaconda3/envs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 600, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Invalid device string: 'cuda:0,1,'
```

I wonder how to set it on multi GPUs properly.

**Comment by galatolofederico** [comment]
Hi. this repo does not support multi GPU as is but it would be very easy to implement a multi GPU forward using [DataParallel](https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html) or a multi node forward using [DistributedDataParallel](https://pytorch.org/docs/stable/generate/torch.nn.parallel.DistributedDataParallel.html#torch.nn.parallel.DistributedDataParallel).

I guess that it would be as easy as adding after line 16 in `generator.py`
```python
self.CLIP = torch.nn.DataParallel(self.CLIP)
```

**Comment by stevenl2** [comment]
I also ran into this issue when attempting to parallelize the model using multi GPUs. I attempted to insert "self.CLIP = torch.nn.DataParallel(self.CLIP)" after line 16, using DataParallel in PyTorch. When putting in this line I encounter the following error: 

on line 54 in run.py:
problem = GenerationProblem(config)

from line 9 in problem.py:
self.generator = Generator(config)

from line 25 in Generator.py: 

AttributeError: "DataParallel" object has no attribute 'encode_text'.

Self.CLIP is a torch.nn.module, which is what DataParallel takes in as a parameter. However, I suspect that DataParallel is not of type torch.nn.module. Therefore, when line 25 attempts to do self.CLIP.encode_text, it does not work. Do you have any ideas as to how we can get past this issue?

Thank you.

**Comment by KevinGoodman** [comment]
Hi stevenl2,
I think that is because the model will be wrapped in DataParallel(). 
![image](https://user-images.githubusercontent.com/43786278/164954876-93739968-7699-472f-8b58-fb6890d52136.png)
Try self.CLIP = torch.nn.DataParallel(self.CLIP).module
