### ISSUE TITLE
Why BigGAN not use discrimnator?

### ISSUE THREAD

**Issue by liuzhengzhe** [galatolofederico/clip-glass#12]
Thanks for your work. I found that the discriminator is helpful to improve the generation quality in StyleGAN setting. Why not use the BigGAN discriminator in the BigGAN setting? 

Thanks.

**Comment by galatolofederico** [comment]
Hi, yeah we pointed out that too in the paper but unfortunately DeepMind did not release the weights of BigGAN's discriminator :disappointed:
