### ISSUE TITLE
Support for GPT-3

### ISSUE THREAD

**Issue by indiv0** [galatolofederico/clip-glass#2]
Hi! Love the project.

I'm in the OpenAI GPT-3 beta, and I was wondering if it's possible for clip-glass to support GPT-3 for the image-to-text task.

If it's possible, I'd love to help set that integration up but I'm not sure where to start.

**Comment by galatolofederico** [comment]
Hey thanks for the suggestion!
It would be amazing to have the GPT-3 model and be able to play with it, unfortunately openai decided to sell it as product. The way i am using GPT-2 here is by setting some context tokens (GPT-2 "latent space") and let it predict the next tokens until the stop token is predicted or a maximum length is reached.
I haven't checked out GPT-3 APIs yet, but i guess that will be possible to integrate it if they have some API calls that let you predict a sentence given some context tokens
