### ISSUE TITLE
how to complete image with text

### ISSUE THREAD

**Issue by molo32** [galatolofederico/clip-glass#3]
how to complete image with text

example: I give an unfilled image from the middle down, then I write
"same image but below, a sketch of the image"

and it generates an image of but half down is a sketch half up.

**Comment by galatolofederico** [comment]
That is not possible using CLIP-GLaSS.
You can generate an image from a text, e.g. "the picture of a dog" and the system will output a picture of a dog (hopefully :smile: )
and you can generate a text from an image, e.g. you give it as input the picture of a dog the system will give you as output something like "the picture of a dog".
The thing that you are asking, using a text prompt and an image as input to generate another image (or another text) is not possible but is for sure interesting. Maybe next paper will be able to do that :smile:
