### ISSUE TITLE
RuntimeError: Method 'forward' is not defined.

### ISSUE THREAD

**Issue by socalledsound** [galatolofederico/clip-glass#5]
your demo notebook worked for me yesterday but today it's giving me this:
RuntimeError: Method 'forward' is not defined.

I really like your implementation!  I don't think I changed anything in what I'm doing.  any ideas?  
i'm pretty much a noob, trying to learn this stuff.
thanks in advance

**Comment by galatolofederico** [comment]
Hi thanks for reporting the problem!
It seems to have something to do with pytorch jit compiler 9af2eb0e8ddab730e2c26f8a81455e43c761208a fixes it!
The notebook should work now :smiley:
