### ISSUE TITLE
GPT-2 output console length?

### ISSUE THREAD

**Issue by smithee771** [galatolofederico/clip-glass#7]
Hi, first thanks for your job :)
I don't know if it's an issue. When I select config "GPT-2", the output text of the prediction seems to be incomplete (example: "the picture of a man who is a man, a man who is a" ) --> seems like something is missing.
Is this a bug? if not, is there a way to increase output length?

many thanks in advance

**Comment by galatolofederico** [comment]
Hi thanks for the interest in the project.
Yes when using `GPT-2` text is generated until the stop-token is predicted or until the maximum number of tokens are produced. Moreover to avoid long sentences the output is always truncated to a maximum number of characters.
This two parameters can be configured in the file `config.py` in the key `GPT2`

```python
    GPT2 = dict(
        task = "img2txt",
        dim_z = 20,
        max_tokens_len = 30,
        max_text_len = 50,
        encoder_size = 50257,
        latent = GPT2LatentSpace,
        model = GPT2,
        use_discriminator = False,
        init_text = "the picture of",
        weights = "./gpt2/weights/gpt2-pytorch_model.bin",
        encoder = "./gpt2/weights/encoder.json",
        vocab = "./gpt2/weights/vocab.bpe",
        stochastic = False,
        algorithm = "ga",
        pop_size = 100,
        batch_size = 25,
        problem_args = dict(
            n_var = 20,
            n_obj = 1,
            n_constr = 20,
            xl = 0,
            xu = 50256
        )
    ),
```

The maximum number of tokens is `max_tokens_len` the maximum text length is `max_text_len`. 
I hope that this is what you were looking for. If you need any further help feel free to open another issue or reach me in private

EDIT:
`GPT2` is also always initially fed with `init_text`

**Comment by smithee771** [comment]
really thanks for your quick help!
