### ISSUE TITLE
Issue when running:  virtualenv --python=python3.6 env && . ./env/bin/activate

### ISSUE THREAD

**Issue by alexp-12** [galatolofederico/clip-glass#8]
Hello,
        When I run the following,

virtualenv --python=python3.6 env && . ./env/bin/activate

I get this output:

RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'

Thoughts?

**Comment by galatolofederico** [comment]
Hi.
It is probably due to the fact that you dont have installed `python3.6`. Depending on your distribution install the correct package and that command should work. Alternatively you can try using a different version of `python3` and it might work anyway
