### ISSUE TITLE
Captioning results not compatible to the paper

### ISSUE THREAD

**Issue by zhuang93** [galatolofederico/clip-glass#9]
Hi,

I tried your model in image captioning using the demo dog image but got a totally different results from your paper. I ran your script 5 times under the default setting and got the following results:
['the picture of the dog\'s body.\n\n"The dog\'s body is’]
['the picture of a dog with a bloated, bloated, bloa’]
["the picture of the puppy's body, with the body's b”]
["the picture of the dog's body, with a large, round”]
["the picture of the dog's body. The dog's body is c”]
['the picture of a dog with a large belly.\n\nâ¼\n\nâ¼\n\nâ¼\n’]

The captioning result shown in your paper is as follows.
![image](https://user-images.githubusercontent.com/33298164/129604598-8b39dbea-a93e-4d73-9439-5523dac2b0b9.png)

Is there any setting modification I need to take for image captioning? Thank you.

**Comment by galatolofederico** [comment]
Hey thanks for checking it out! 
In the paper i have used the same settings of this repo.
The search is carried out using a genetic algorithm so it is normal that every run it finds a different solution. 
The only way to replicate the paper results would be using the same seed for the rng. Maybe i have saved them I don't remember, right now i am on vacation but when I will be back in the office I will look for them.
I usually save all the seeds for the experiments so it is very likely that i saved them

**Comment by zhuang93** [comment]
> Hey thanks for checking it out!
> In the paper i have used the same settings of this repo.
> The search is carried out using a genetic algorithm so it is normal that every run it finds a different solution.
> The only way to replicate the paper results would be using the same seed for the rng. Maybe i have saved them I don't remember, right now i am on vacation but when I will be back in the office I will look for them.
> I usually save all the seeds for the experiments so it is very likely that i saved them

Thanks for your quick response. Hope to hear your update after your vacation. (BYW, Have a good vacation!) I have one more question about why it will generate non-English word or symbol?
